apiVersion: v1
kind: Namespace
metadata:
  name: kn-dbg
  labels:
    knative-eventing-injection: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgdumper
  namespace: kn-dbg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msgdumper
  template:
    metadata:
      labels:
        app: msgdumper
    spec:
      containers:
        - name: msgdumper
          image: github.com/Experiments/msgdumper

---

kind: Service
apiVersion: v1
metadata:
  name: msgdumper
  namespace: kn-dbg
spec:
  selector:
    app: msgdumper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: msgdumper
  namespace: kn-dbg
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: msgdumper
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: msgdumper
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: msgdumper
  namespace: kn-dbg

---

apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    run: curl
  name: curl
  namespace: kn-dbg
spec:
  containers:
  - image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: curl
    resources: {}
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: msgdumper
  namespace: kn-dbg
spec:
  # Our Cloud Event parsing library seems to have a bug and forces to put type and source in double
  # quotes (as it thinks the actual value is `"foo"`, not `foo`).
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: msgdumper

    